### ISSUE TITLE
account koppelen met QR werkt niet

### ISSUE THREAD

**Issue by dataclaud123** [floronnl/VERA-issues#100]
Ik zie wel de code en de QR scanner, maar er gebeurt niks.
Volla phone 22
Android versie 13
Op andere telefoons bleef de locatie steeds vaststaan op 1 punt

**Comment by Desharin** [comment]
De QR scanner lijkt niet te werken op apparaten zonder Google Play Services. Er komt een fix aan.

**Comment by Desharin** [comment]
Dit zou in versie 1.7.4 weer moeten werken, graag hoor ik het als er nog problemen zijn.
