### ISSUE TITLE
Invoerveld voor een collectienummer

### ISSUE THREAD

**Issue by ghost** [floronnl/VERA-issues#59]
Voor soortgroepen waar een exemplaar van verzameld wordt, is het prettig als je een collectie nummer kan toevoegen. 
Huidige workaround is het gebruik van het opmerkingenveld, maar het is handiger als je hier een apart veld voor heb.

**Comment by Desharin** [comment]
@laurenssparrius Ik zie hier het voordeel wel van in, maar weet niet hoe vaak dit gebruikt wordt. Is dit iets wat we willen?

**Comment by laurenssparrius** [comment]
Beter is dat de waarnemer dit thuis in de Verspreidingsatlas invoert. Met een collectienummer wordt een herbarium of andere manier van permanente opslag van bewijs bedoeld. Dit is typisch iets wat je pas thuis beslist na determinatie.
