### ISSUE TITLE
Waarnemer loopt niet binnen binnen plot, terwijl dat wel zo is

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#68]
Specifiek voor LMFa route Berkheide 86-464 [5061] https://www.verspreidingsatlas.nl/projecten/floron/lmfa/transect.aspx?id=5061
Het lukt hier niet om waarnemingen in te voeren vanwege de foutmelding "Locatie buiten opgegeven plot", ook nadat het invoermasker een ruime cirkel van 1500 m rond het plot is geworden. De waarneming staat precies op de route. Moderne telefoon  Samsung Galaxy S20 FE 4G

**Comment by laurenssparrius** [comment]
Mogelijke oplossing is dat gebruikers deze controle kunnen uitzetten voor lijntransecten.

**Comment by Desharin** [comment]
Het is mij nog niet gelukt dit te reproduceren. Ik kan bij deze route gewoon waarnemingen invoeren.

![image](https://github.com/floronnl/VERA-issues/assets/5775267/e8e6b19f-0f39-46dd-a88e-d7e719f82341)

Indien dit probleem zich blijft voordoen kunnen we de locatiecontrole voor het LMF-a protocol uitzetten.

**Comment by laurenssparrius** [comment]
OK, laat deze dan maar even zitten
