### ISSUE TITLE
Toetsenbord blijft soms hangen

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#71]
Bij sommige gebruikers blijft het toetsenbord hangen tijdens het invoeren. -- gemeld door diverse gebruikers.

**Comment by laurenssparrius** [comment]
Is iets van de laatste tijd mogelijk na een Android-update. Kijk nog eens naar de correcte manier van het uitlezen van het toetsenbord.

**Comment by Desharin** [comment]
Wat wordt hiermee bedoeld? Blijft het toetsenbord foutief openstaan, of doen te toetsen op het toetsenbord het niet?

**Comment by laurenssparrius** [comment]
Als je langere tijd waarnemingen invoert (toetsenbord staat 100% van de tijd uitgeklapt) , dan bevriest het invoerscherm vaak na 10-30 minuten. Gebruiker kan dan op de terugknop rechtsboven tikken en vervolgens op het plusje linksonder om weer verder te gaan.

Misschien is een oplossing om het toetsenbord na het opslaan van een waarneming te sluiten en te herstarten? (nieuwe instance).

**Comment by Desharin** [comment]
We doen nu het toetsenbord dicht en weer open om zo een nieuwe instance te maken.
