### ISSUE TITLE
Foto bijgevoegd bij waarneming: knop 'waarneming opslaan' duurt lang

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#72]

**Comment by Desharin** [comment]
Testen met trage telefoon

**Comment by Desharin** [comment]
We zijn nu van library gewisseld om het compressen van de foto's sneller te laten verlopen. Ook wordt duidelijker aangeven dat de telefoon bezig is zodat het niet lijkt alsof de app niet meer reageert.
