### ISSUE TITLE
Radar blijft hangen als scherm uitgezet wordt en weer aan

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#77]
Om te reproduceren (lukt niet altijd)
* open het scherm 'radar' en wacht tot de stippen verschijnen
* klik op knop zijkant telefoon) op het scherm uit te zetten
* klik nogmaals om de telefoon aan te zetten
* nu hangt het scherm en de app moet handmatig worden afgesloten

**Comment by Desharin** [comment]
Wordt mogelijk veroorzaakt door https://github.com/flutter/flutter/issues/98865 of https://github.com/flutter/flutter/issues/105965. Hopelijk lost de upgrade van de Google Maps SDK dit op.
