### ISSUE TITLE
Oorsprong veld

### ISSUE THREAD

**Issue by ElsHeijman** [floronnl/VERA-issues#84]
Graag de optie Autochtoon toevoegen naar aanleiding van de leergang Autochtone bomen en struiken van Bert Maes in Drenthe

**Comment by laurenssparrius** [comment]
We slaan karteringen van Bert Maes e.a. onder een apart protocol op, omdat de data anders niet meer in de NDFF terug te vinden is. Als er nieuwe velddata worden verzameld, dan even contact opnemen met mij, want dit kan nu niet met de bestaande apps.

**Comment by ElsHeijman** [comment]
Dag Laurens,

Bedankt voor je reactie.

Deze vraag kwam naar voren in de Leergang Autochtone bomen en struiken die door Bert Maes afgelopen jaar gegeven is o.a. in Drenthe en kwam voort uit een discussie over vastlegging en validatie.

Ik zal het terugkoppelen aan Anja Verbers van  Landschapsbeheer Drenthe, volgend jaar gaat deze leergang nogmaals plaats vinden. 

Wat mij betreft kan dit issue gesloten worden.

Bedankt en groet,

Els

 

 

Van: Laurens Sparrius ***@***.***> 
Verzonden: zondag 22 oktober 2023 10:46
Aan: floronnl/VERA-issues ***@***.***>
CC: ElsHeijman ***@***.***>; Author ***@***.***>
Onderwerp: Re: [floronnl/VERA-issues] Oorsprong veld (Issue #84)

 

We slaan karteringen van Bert Maes e.a. onder een apart protocol op, omdat de data anders niet meer in de NDFF terug te vinden is. Als er nieuwe velddata worden verzameld, dan even contact opnemen met mij, want dit kan nu niet met de bestaande apps.
