### ISSUE TITLE
Meerdere foto's selecteren

### ISSUE THREAD

**Issue by Desharin** [floronnl/VERA-issues#87]
Voeg de mogelijkheid toe om meerdere foto's uit de galerij te selecteren om in 1x aan een waarneming toe te voegen.

**Comment by laurenssparrius** [comment]
is dit al doorgevoerd in 1.6.0?

**Comment by Desharin** [comment]
Nee nog niet. Volgens mij zijn hier geen grote aanpassingen voor nodig en kan dit relatief makkelijk doorgevoerd worden.

**Comment by laurenssparrius** [comment]
Test OK
