### ISSUE TITLE
Account koppelen pincode meesturen

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#88]
De API-key wordt in het geval van een foute pincode niet in de app opgeslagen en de gebruiker krijgt een foutmelding.

Echter, op dit moment wordt er bij een foute pincode wel altijd een API-key gegenereerd en opgeslagen in VA alsof de pincode correct was. Om de pincode bij het koppelen van een account aan beide zijden te kunnen controleren, moet deze worden toegevoegd aan de queryparamaters van account_screen.dart

**Comment by Desharin** [comment]
De pincode zal in versie 1.7.0 worden gestuurd in de queryparameters als
`'pincode': '1234'`

**Comment by laurenssparrius** [comment]
Het script om de pincode te controleren is nu in de Verspreidingsatlas aangepast. De huidige versie blijft nog een tijdje werken als er geen pincode wordt meegestuurd.

**Comment by laurenssparrius** [comment]
Test OK
