### ISSUE TITLE
Vegetatieopname

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#90]
Mogelijkheid om een vegetatieopname te maken met verschillende schalen.

VA: nieuw intern protocollen voor vegetatieopname

Vera: nieuw formulier. Hiertoe kopie maken van de Nectarindex (kenmerk van vegetatieopname is dat elke soort maar één keer wordt ingevoerd en dat de abundantie achteraf gemakkelijk kan worden aangepast)

Soortgroepen: vaatplanten, mossen, korstmossen en algen door elkaar heen in te voeren

Abundantieschalen (vooraf in het formulier eenmalig vast te leggen en niet meer te veranderen):
* Tansley
* Tansley decimaal
* Braun-Blanquet (B,D,S)

Aanvullende kopgegevens:
suggesties voor veldnamen staan hier: https://woordenboekbeheer.ndff.nl/codes.php?identity=http://ndff-ecogrid.nl/codes/keys/group/vegetation

(1) Locatietype
(2) Coordinaat Startpunt (x, y) RD in meters
(3) Coordinaat Eindpunt (x, y) RD in meters
(4) Lengte in m standaard 2
(5) Breedte in m standaard 2
(6) Opnamenummer
(7) Gebiedsnaam
(8) Habitat (IPI, zoals bij waarnemingen)
(9) Bedekking totaal (%)
(10) strooisellaag %
(11) Bedekking boomlaag (%)
(12) Bedekking struiklaag (%)
(13) Bedekking kruidlaag (%)
(14) Bedekking moslaag (%)
(15) Hoogte boomlaag (m)
(16) Hoogte struiklaag (m)
(17) Hoogte kruidlaag (cm)
(18) Bedekking onderwaterplanten (%)
(19) Bedekking in de bodem wortelende drijfbladplanten (%)
(20) Bedekking kroos (%)
(21) Bedekking draadalg (%)
(22) Bedekking emergenten (%)
(23) Dichtheid oevervegetatie (%)
(24) Percentage houtig (%)
(25) Percentage beschaduwd (%)
(26) Breedte oeverzone (m)
(27) Breedte waterzone (m)
(28) Mos/korstmos meegenomen : 0 = geen mossen en korstmossen opgenomen 1 = mossen én korstmossen opgenomen 2 = mossen opgenomen 3 = korstmossen opgenomen 4 = mossen en/of korstmossen onvolledig opgenomen
(29) Beheer: 01 = niets doen 02 = begrazing 03 = begrazing door runderen en paarden 04 = begrazing door schapen 05 = hakhout- en griendbeheer 06 = maaibeheer 07 = bemesting 08 = slootschoning (jaarlijks) 09 = onbekend

**Comment by Desharin** [comment]
Heb je liever locatietype, startpunt, beginpunt apart, of zou je liever een WKT aangeleverd krijgen? Dus bijvoorbeeld POINT(123456 456789) of LINESTRING(123456 456789, 123489, 456710)

**Comment by laurenssparrius** [comment]
Je mag het combineren in een POINT of LINESTRING. Uiteindelijk krijgen de waarnemingen ook die geometrie mee. Het is wel belangrijk dat de eindpunt-coordinaten optioneel zijn. Als er alleen een startpunt is, dan wordt de geometrie POINT, anders LINESTRING (met twee punten).

**Comment by Desharin** [comment]
Welke namen moeten deze velden hebben voor de Verspreidingsatlas API?

**Comment by laurenssparrius** [comment]
(1) WKT location:   **wkt**   *

(4) Lengte in m standaard 2  **plot_length**   * 
(5) Breedte in m standaard 2    **plot_width**   *
(6) Opnamenummer   **plotnr** 
(7) Gebiedsnaam    **locationname** 
(8) Habitat (IPI, zoals habitat bij waarnemingen voor vaatplanten)   **habitat**
(9) Bedekking totaal (%)   **cover_total**
(10) strooisellaag %   **cover_litter**  * 
(11) Bedekking boomlaag (%)   **cover_treelayer**
(12) Bedekking struiklaag (%)   **cover_shrublayer**
(13) Bedekking kruidlaag (%)   **cover_herblayer**
(14) Bedekking moslaag (%)    **cover_mosslayer**
(15) Hoogte boomlaag (m)   **height_treelayer_high**
(16) Hoogte struiklaag (m)    **height_shrublayer_low**
(17) Hoogte kruidlaag (cm)   **height_herblayer_low**
(18) Bedekking onderwaterplanten (%)        **cover_submerged_vegetation**  * 
(19) Bedekking in de bodem wortelende drijfbladplanten (%)       **cover_floating_vegetation**  * 
(20) Bedekking kroos (%)       **cover_duckweed**  * 
(21) Bedekking draadalg (%)       **cover_algae**  * 
(22) Bedekking emergenten (%)     **cover_emergent**  * 
(23) Dichtheid oevervegetatie (%)    **plot_percentage_bank_vegetation**  * 
(24) Percentage houtig (%)   **waterbody_percentage_wooded**  * 
(25) Percentage beschaduwd (%)  **waterbody_shading**
(26) Breedte oeverzone (m) **waterbody_bank_width**  * 
(27) Breedte waterzone (m) **waterbody_width**
(28) Mos/korstmos meegenomen  **mosslayer_info**  : 0 = geen mossen en korstmossen opgenomen 1 = mossen én korstmossen opgenomen 2 = mossen opgenomen 3 = korstmossen opgenomen 4 = mossen en/of korstmossen onvolledig opgenomen
(29) Beheer  **management**  : 01 = niets doen 02 = begrazing 03 = begrazing door runderen en paarden * 04 = begrazing door schapen * 05 = hakhout- en griendbeheer 06 = maaibeheer * 07 = bemesting * 08 = slootschoning (jaarlijks) * 09 = onbekend *

* (nog) niet in NDFF Woordenboek

**Comment by Desharin** [comment]
Ik heb hier een test van klaarstaan, is de API klaar om die te ontvangen?

**Comment by Desharin** [comment]
Oh wat bedoelde je trouwens met algen? Ik heb nu wieren gedaan.

**Comment by laurenssparrius** [comment]
Inderdaad: wieren / soortgroep W

Op vr 26 apr 2024 om 12:05 schreef Dion van der Hak <
***@***.***>:

**Comment by laurenssparrius** [comment]
De API is nog niet helemaal klaar om alle kopgegevens op te slaan, maar je
kunt wel al testen. De soortenlijst zou gewoon ingelezen moeten worden. Het
helpt mij ook om een upload klaar te hebben staan die ik kan gebruiken om
te testen.

Op vr 26 apr 2024 om 11:42 schreef Dion van der Hak <
***@***.***>:

**Comment by Desharin** [comment]
Ok, ik heb er een geupload

**Comment by laurenssparrius** [comment]
Hoi Dion,

Er komt een foutmelding op deze uri:
http://ndff-ecogrid.nl/codes/abundance/cover/tansley/-   die in de test in
de tweede waarneming zat.

Het liggende streepje is bij jou een ander teken (dat er erg op lijkt UTF
ASC 226 128 147). Als je het eindstreepje uit de uri hierboven kopieert,
dan heb je de juiste te pakken (ASC 45). Als je de
abundantiecodes automatisch ophaalt en niet in de code hebt staan, dan moet
ik het mogelijk op een andere manier oplossen.

Groet, Laurens

Op di 30 apr 2024 om 10:49 schreef Dion van der Hak <
***@***.***>:

**Comment by Desharin** [comment]
Hey das een grappige, ik stuur zo een nieuwe poging.
Blijkbaar staar ie verkeerd hier:
[https://woordenboek.ndff.nl/codes.php?showparents=1&identity=http://ndff-ecogrid.nl/codes/abundance/cover/tansley/%E2%80%93](https://woordenboek.ndff.nl/codes.php?showparents=1&identity=http://ndff-ecogrid.nl/codes/abundance/cover/tansley/%E2%80%93)

**Comment by laurenssparrius** [comment]
OK, dan moeten we dat misschien maar zo laten, en de code aanpassen in de VA

**Comment by laurenssparrius** [comment]
De rest van de test is geslaagd en het laadscript aangepast. Dus staat nog open voor jou:

* nieuwe velden in JSON output in aparte subcategorie 'formattributes'
* code voor Tansley '-' zo laten, dus http://ndff-ecogrid.nl/codes/abundance/cover/tansley/%E2%80%93
* mocht je in de Braun-Blanquet schaal een abundantiecode '0' hebben, dan die graag weglaten (wordt niet gebruikt)

**Comment by Desharin** [comment]
Top, ik heb weer een nieuwe test gestuurd.

**Comment by Desharin** [comment]
Als deze goed wil ik de app wel naar onze toestellen uitrollen voor een interne test

**Comment by laurenssparrius** [comment]
Ja, prima! De laatste upload van een vegetatieopname werkte goed de opname komt ook goed door in de andere onderdelen van de NDFF

**Comment by laurenssparrius** [comment]
Ik heb deze nu uitgerold naar de Open test. Kijken of het vandaag nog lukt om deze beoordeeld te krijgen

**Comment by laurenssparrius** [comment]
Paar details:
* Wanneer in de lijstweergave van een Braun-Blanquet opname abundantie '+' is gekozen, dan werkt de plus-knop niet. Zou naar 1 moeten gaan.
* Idem, Wanneer deze op 1 staat, werkt de min-knop niet. Zou naar + moeten gaan.
* Scherm nieuw formulier: lijst met formuliertypen -> Stoepplantjes verwijderen
* Scherm nieuw formulier: lijst met formuliertypen -> Braun/Blanquet (B,D,S) -> Braun-Blanquet
* Standaardwaarde voor Lengte (m) en Breedte (m) toch maar weghalen (was 2)

**Comment by Desharin** [comment]
> * Wanneer in de lijstweergave van een Braun-Blanquet opname abundantie '+' is gekozen, dan werkt de plus-knop niet. Zou naar 1 moeten gaan.

Oh ja, dat komt natuurlijk omdat ie die 0 ertussenuit heb gesloopt, ik ga het fixen

**Comment by Desharin** [comment]
@laurenssparrius Als je tevreden bent met deze versie kunnen we 'm wat mij betreft uitrollen naar productie.

**Comment by laurenssparrius** [comment]
Zou je dit nog willen aanpassen:  Braun/Blanquet -> Braun-Blanquet  
Dan is het goed en kan het in productie.
