### ISSUE TITLE
QR-code scanner geeft wit scherm op sommige telefoons

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#95]
Betrof een Moto X4 met Android versie 9. Het scannen van de QR-code is ondanks het niet tonen van het camerabeeld wel gelukt.

**Comment by Rinodina** [comment]
Some on my Samsung A7 (2017)

**Comment by Rinodina** [comment]
On Tue, 13 Aug 2024 05:56:40 -0700, you wrote:

>Voor de bèta testers is er een nieuwe versie beschikbaar waarin deze bug verholpen zou moeten zijn. Ik heb helaas geen telefoon met de juiste Android versie om dit te testen. Graag hoor ik of het probleem in versie 1.7.2 naar tevredenheid is opgelost.

QR scannen lukt nu wel, maar de koppeling mislukt steeds.
Mijn telefoon is een Samsung Galaxy A7 met Android versie 7.0.

Met deze telefoon is het mij eerder wel gelukt mij aan te melden. Hij
staat zelfs 3 keer(!) vermeld in mijn profiel (waar ik hem overigens niet
meer uit kan verwijderen).

Heel handig, die QR aanmeldmethode, maar de mogelijkheid bieden om het op
de oude manier te doen lijkt me wel handig.

Groeten,
Arjan

**Comment by Desharin** [comment]
Deze problemen zouden in versie 1.7.3 opgelost moeten zijn, laat maar weten als je nog tegen problemen aanloopt
