### ISSUE TITLE
Soortgroep Kranswieren (K) kunnen invoeren in vegetatieopnamen

### ISSUE THREAD

**Issue by laurenssparrius** [floronnl/VERA-issues#96]
Verzoek is om de soorten uit de soortgroep kranswieren ook invoerbaar te maken in de drie verschillende formulieren voor vegetatieopnamen.

**Comment by Desharin** [comment]
Deze wijziging is nu beschikbaar in versie 1.7.1

**Comment by laurenssparrius** [comment]
Wow, fantastisch, dankjewel!
