### ISSUE TITLE
Toevoegen schalen voor abundatie (vegetatieopname)

### ISSUE THREAD

**Issue by Rietbas** [floronnl/VERA-issues#97]
Naast de Floronschaal voor losse waarnemingen zou het handig zijn om soorten van een opnamevlak te kunnen invoeren. 
Naast meer opties voor aantal/abundantieschalen  (Braun Blanquet/Tansley) zou dan evt ook een opnamenummer en proefvlakgrootte moeten kunnen worden genoteerd.

**Comment by laurenssparrius** [comment]
Inmiddels is het mogelijk om vegetatieopnamen in te voeren en (na uploaden) te exporteren als kruistabel
